kind: Pod
apiVersion: v1
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: public.ecr.aws/amazonlinux/amazonlinux:2
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch
      command: ["sleep", "1000000"]
  volumes:
    - name: scratch
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-pod
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: gp2
            volumeMode: Filesystem
            resources:
              requests:
                storage: 1Gi
